//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCProject.AppService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ServiceRequestDATA", Namespace="http://schemas.datacontract.org/2004/07/AppService.DATA")]
    [System.SerializableAttribute()]
    public partial class ServiceRequestDATA : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ACTIONField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string APPROVEIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime CREATEDATEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DESCRIPTIONField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MVCProject.AppService.ServiceRequestDATA[] LSTREQField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string REQCODEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TITLEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string USERIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ACTION {
            get {
                return this.ACTIONField;
            }
            set {
                if ((object.ReferenceEquals(this.ACTIONField, value) != true)) {
                    this.ACTIONField = value;
                    this.RaisePropertyChanged("ACTION");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string APPROVEID {
            get {
                return this.APPROVEIDField;
            }
            set {
                if ((object.ReferenceEquals(this.APPROVEIDField, value) != true)) {
                    this.APPROVEIDField = value;
                    this.RaisePropertyChanged("APPROVEID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CREATEDATE {
            get {
                return this.CREATEDATEField;
            }
            set {
                if ((this.CREATEDATEField.Equals(value) != true)) {
                    this.CREATEDATEField = value;
                    this.RaisePropertyChanged("CREATEDATE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DESCRIPTION {
            get {
                return this.DESCRIPTIONField;
            }
            set {
                if ((object.ReferenceEquals(this.DESCRIPTIONField, value) != true)) {
                    this.DESCRIPTIONField = value;
                    this.RaisePropertyChanged("DESCRIPTION");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MVCProject.AppService.ServiceRequestDATA[] LSTREQ {
            get {
                return this.LSTREQField;
            }
            set {
                if ((object.ReferenceEquals(this.LSTREQField, value) != true)) {
                    this.LSTREQField = value;
                    this.RaisePropertyChanged("LSTREQ");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string REQCODE {
            get {
                return this.REQCODEField;
            }
            set {
                if ((object.ReferenceEquals(this.REQCODEField, value) != true)) {
                    this.REQCODEField = value;
                    this.RaisePropertyChanged("REQCODE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TITLE {
            get {
                return this.TITLEField;
            }
            set {
                if ((object.ReferenceEquals(this.TITLEField, value) != true)) {
                    this.TITLEField = value;
                    this.RaisePropertyChanged("TITLE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string USERID {
            get {
                return this.USERIDField;
            }
            set {
                if ((object.ReferenceEquals(this.USERIDField, value) != true)) {
                    this.USERIDField = value;
                    this.RaisePropertyChanged("USERID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AppService.IRequestService")]
    public interface IRequestService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRequestService/DoWork", ReplyAction="http://tempuri.org/IRequestService/DoWorkResponse")]
        void DoWork();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRequestService/DoWork", ReplyAction="http://tempuri.org/IRequestService/DoWorkResponse")]
        System.Threading.Tasks.Task DoWorkAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRequestService/GetRequestByCondition", ReplyAction="http://tempuri.org/IRequestService/GetRequestByConditionResponse")]
        MVCProject.AppService.ServiceRequestDATA GetRequestByCondition(MVCProject.AppService.ServiceRequestDATA order);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRequestService/GetRequestByCondition", ReplyAction="http://tempuri.org/IRequestService/GetRequestByConditionResponse")]
        System.Threading.Tasks.Task<MVCProject.AppService.ServiceRequestDATA> GetRequestByConditionAsync(MVCProject.AppService.ServiceRequestDATA order);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IRequestServiceChannel : MVCProject.AppService.IRequestService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RequestServiceClient : System.ServiceModel.ClientBase<MVCProject.AppService.IRequestService>, MVCProject.AppService.IRequestService {
        
        public RequestServiceClient() {
        }
        
        public RequestServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RequestServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RequestServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RequestServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void DoWork() {
            base.Channel.DoWork();
        }
        
        public System.Threading.Tasks.Task DoWorkAsync() {
            return base.Channel.DoWorkAsync();
        }
        
        public MVCProject.AppService.ServiceRequestDATA GetRequestByCondition(MVCProject.AppService.ServiceRequestDATA order) {
            return base.Channel.GetRequestByCondition(order);
        }
        
        public System.Threading.Tasks.Task<MVCProject.AppService.ServiceRequestDATA> GetRequestByConditionAsync(MVCProject.AppService.ServiceRequestDATA order) {
            return base.Channel.GetRequestByConditionAsync(order);
        }
    }
}
